### PR TITLE
add skip/2 as the counterpart to limit/2

### PR DESCRIPTION
**Pull request by itchyny**
This PR implements `skip/2` as the counterpart of `limit/2`. I also changed the behavior of `limit/2` with negative count to emit an error, like `nth/2` does. Also, I redefined `nth/2` using `skip/2` to minimize the impact of growth of builtin filters.

### CODE REVIEW

**Review by wader — APPROVED** [review]
Like it 👍 

BTW i'm looking at #3179 but i'm new to the jq vm so taking some times to understand it

**Comment by itchyny** [comment]
Any comments from another maintainer?

**Comment by pkoppstein** [comment]
Please merge! Thank you!

**Comment by itchyny** [comment]
Thank you!

**Pull request merged**
