### PR TITLE
C99 compatibility enhancements for the configure script

### PR DESCRIPTION
**Pull request by fweimer-rh**
Related to:

* https://fedoraproject.org/wiki/Changes/PortingToModernC
* https://fedoraproject.org/wiki/Toolchain/PortingToModernC

### CODE REVIEW

**Comment by thesamesam** [comment]
I only found that one accidentally too. Yeah, I prefer the approach in this one.

cc @kraj

**Comment by kraj** [comment]
Yes this is clearly better way please go ahead

**Comment by itchyny** [comment]
Would you rebase against the latest master, since this is a fix to a building script? Thank you.

**Comment by fweimer-rh** [comment]
@itchyny Should now be properly rebased.

**Review by itchyny — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
