### PR TITLE
Invalid checksum file

### PR DESCRIPTION
**Pull request by kamontat**
fix(checksum): checksum file must contains 2 space otherwise shasum command will failed

### CODE REVIEW

**Comment by wader** [comment]
Should probably fix it here also https://github.com/jqlang/jq/blob/24e6e6ea3989ccd1b83be9e61f2666d016bac330/.github/workflows/ci.yml#L372

**Comment by kamontat** [comment]
> Should probably fix it here also

@wader Fixed.

**Review by wader — APPROVED** [review]
@itchyny or @nicowilliams should probably have a look also

**Review by itchyny — APPROVED** [review]
Thank you.

**Pull request merged**
