### PR TITLE
Fix leak on invalid input for strftime, strflocaltime and mktime

### PR DESCRIPTION
**Pull request by wader**

### CODE REVIEW

**Comment by wader** [comment]
valgrind log:
```
==11329== 53 bytes in 1 blocks are definitely lost in loss record 1 of 2
==11329==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==11329==    by 0x11AE1C: jv_mem_alloc (jv_alloc.c:122)
==11329==    by 0x116901: jvp_string_alloc (jv.c:1082)
==11329==    by 0x116901: jvp_string_append (jv.c:1165)
==11329==    by 0x117A9B: jv_string_concat (jv.c:1436)
==11329==    by 0x136D3F: constant_fold (parser.y:242)
==11329==    by 0x136D3F: gen_binop (parser.y:256)
==11329==    by 0x13AC8F: yyparse (parser.y:612)
==11329==    by 0x13B1E2: jq_parse (parser.y:1015)
==11329==    by 0x129994: load_program (linker.c:406)
==11329==    by 0x1134C0: jq_compile_args (execute.c:1239)
==11329==    by 0x1156B2: run_jq_tests (jq_test.c:129)
==11329==    by 0x115FBE: jq_testsuite (jq_test.c:34)
==11329==    by 0x10FE0B: main (main.c:582)
==11329== 
FAIL tests/jqtest (exit status: 1)
```

Wonder if the new tests exposed some additional leak? ... also time for me to get a local valgrind setup

**Comment by emanuele6** [comment]
<s>I have not tested this, but I think the issue is that you should also free `a`</s>Nevermind `j` is `a`.

**Comment by wader** [comment]
Ah yeah that makes sense. Ill fix my local valgrind and reproduce it and then fix

**Comment by wader** [comment]
> I have not tested this, but I think the issue is that you should also free `a`Nevermind `j` is `a`.

Oh that confused me also

**Comment by emanuele6** [comment]
@wader 
```diff
diff --git a/src/builtin.c b/src/builtin.c
index 0143b88..b797c9b 100644
--- a/src/builtin.c
+++ b/src/builtin.c
@@ -1633,8 +1633,10 @@ static jv f_strflocaltime(jq_state *jq, jv a, jv b) {
     return ret_error2(a, b, jv_string("strflocaltime/1 requires a string format"));
   }
   struct tm tm;
-  if (!jv2tm(a, &tm))
+  if (!jv2tm(a, &tm)) {
+    jv_free(b);
     return jv_invalid_with_msg(jv_string("strflocaltime/1 requires parsed datetime inputs"));
+  }
   const char *fmt = jv_string_value(b);
   size_t alloced = strlen(fmt) + 100;
   char *buf = alloca(alloced);
```

**Comment by emanuele6** [comment]
<s>Same problem in `strftime/1`</s>

Never mind, only in `strflocaltime/1`.

`strftime/1` doesn't have the same problem because it uses `return ret_error(b, jv_string("strftime/1 requires parsed datetime inputs"));` instead of `jv_invalid_with_msg()`; that is a better fix.

**Comment by wader** [comment]
Yeap will use `ret_error`, testing now

**Review by emanuele6 — APPROVED** [review]
LGTM

**Comment by wader** [comment]
Thanks for the help! weirdly i get some other leak locally, will investigate separately

**Comment by emanuele6** [comment]
fwiw, on all the CI workflows, and on my PC, `make check` doesn't detect any problems

**Comment by wader** [comment]
> fwiw, on all the CI workflows, and on my PC, `make check` doesn't detect any problems

Yeah not sure what is going on, this seems to fix the leak locally for me https://github.com/jqlang/jq/pull/2764

**Pull request merged**
