### PR TITLE
Set field color using JQ_COLORS

### PR DESCRIPTION
**Pull request by haguenau**
This should address #1739.

As far as I can tell, this works and passes the test suite (which I updated to test this specific addition). There is a chance that the code changes are not perfect; for example I'm not sure how much sense it makes to have introduced an enum member `JV_KIND_FIELD` for this (although it keeps the code mostly regular).

### CODE REVIEW

**Comment by haguenau** [comment]
Cool. Please don't hesitate to let me know if you see changes that you think would make sense.

**Comment by ericpruitt** [comment]
@nicowilliams , would you be willing to merge an updated version of this patch or even https://github.com/stedolan/jq/pull/1977?

**Comment by ericpruitt** [comment]
I'm attaching a patch that's a updated version of this PR for anyone that builds jq themselves. Thanks, @haguenau, for the original code.

[jq-src-JQ_COLORS-field-color.patch.txt](https://github.com/stedolan/jq/files/4111550/jq-src-JQ_COLORS-field-color.patch.txt)

**Comment by t829702** [comment]
is this abandonded?

**Comment by ericpruitt** [comment]
Depends on what you mean by abandoned. I'm still using this patch, and the last time I synchronized my copy of jq with the upstream repo, the patch still applied cleanly, so I haven't needed to post any updates here.

**Comment by zpangwin** [comment]
> is this abandoned?

I see commits on the repo as recently as a month and a half ago... guessing the dev's are just busy / this isn't a high priority for them. I'm not familar with travis builds but I see that it has something flagged for "continuous-integration/travis-ci/pr — The Travis CI build could not complete due to an error" ... could be something as simple as that holding things back.

Anyway, I hope folks are able to make it happen too... can't stand the hard-to-read dark blue key/property names on my  terminal. Even if the default was a bright purple, that would at least have decent contrast on light and dark backgrounds. Obviously customizing would be better but I probably wouldn't have bothered to look this up / subscribe to the ticket and PR if the defaults were more reasonable :-)

Guess it's back to `alias jq='/usr/bin/jq --monochrome-output'` for me until this makes it in / someone posts idiot-proof build instructions that I can follow for patching lol

**Comment by haguenau** [comment]
I have not followed jq development very closely since submitting this pull request two years ago. I must admit I do not fully understand [nicowilliam's reasons for having to think more about this](https://github.com/stedolan/jq/pull/1791#issuecomment-455642415); I assume the change is somehow unclean.

If there is interest, I would be happy to look into reworking the change so that it applies successfully to the current code.

**Comment by fdevibe** [comment]
I would, too, be very interested in hearing counter-arguments against this. The hard-coded field color is very difficult to read on a dark background, and dark backgrounds are pretty common in what I would assume jq's user base is.

Changing the field color is also something quite a few people request in https://stackoverflow.com/questions/51338701/how-do-i-customize-the-colors-used-by-jq-c

**Comment by NickCis** [comment]
Really looking into getting this merge, Can I offer any help with it?.

**Comment by itchyny** [comment]
Added to the next release milestone. Needs rebasing though.

**Comment by ericpruitt** [comment]
I'll open a PR later today with my latest version of the patch.

**Comment by haguenau** [comment]
> I'll open a PR later today with my latest version of the patch.

Much appreciated. Given how old this pull request is, I expect a lot
of changes would be needed to make it up to date, so I am very happy
to see you offer to take care of this.

**Comment by ericpruitt** [comment]
I've opened https://github.com/jqlang/jq/pull/2638.

**Comment by itchyny** [comment]
Taking a careful look into this patch, I finally understand why this is hard to merge. This patch adds `JV_KIND_FIELD` to `jv_kind`, but this is not what `jv_kind` is intended. This enum type is a basic and core type of JSON representation in jq, and such a new value shouldn't be added just for colors. So I propose; do not touch `jv_kind` and `color_kinds`, but `color_bufs` can have 8 (==`sizeof(color_kinds)/sizeof(color_kinds[0]) + 1`) entries, and `FIELD_COLOR` can be `colors[sizeof(color_kinds)/sizeof(color_kinds[0])]` or simply `colors[7]`.

**Pull request closed without merging**
