### PR TITLE
manual.yml: revise section on identity, clarifying what might change

### PR DESCRIPTION
**Pull request by pkoppstein**
Mostly clarifications w.r.t. numbers.

The anomalous behavior of leading minus signs is documented, with an explicit notice that this will probably change.

### CODE REVIEW

**Comment by pkoppstein** [comment]
This PR does not include any changes to manual.yml that were not in the PR it supersedes, namely https://github.com/jqlang/jq/pull/2731, which was closed as it had a "merge" commit.

See also #2704

**Comment by nicowilliams** [comment]
Thanks!

**Comment by pkoppstein** [comment]
@nicowilliams - And thanks for the pointer to your git gist.  I dread the day, though, when I understand git.

**Comment by nicowilliams** [comment]
@pkoppstein and I dread people not understanding git :)  Look, I'm not saying it's got a lovely UI or anything, but I am saying that you can come to grok it.  I believe I've a fairly different take than most who try to explain git, though of course, my approach might not work for you, but do give it a try.

**Pull request merged**
