### PR TITLE
Use jinja2 ==3.0.2 for now

### PR DESCRIPTION
**Pull request by emanuele6**
We are using some deprecated jinja2 features that have been removed in newer versions.

### CODE REVIEW

**Comment by emanuele6** [comment]
The CI is all green. =)

**Comment by nicowilliams** [comment]
You'll have to rebase and revert my revert :(

**Comment by emanuele6** [comment]
Done :+1:

**Comment by emanuele6** [comment]
Wait, I didn't rebase correctly. (I only rebased without regenerating `Pipfile.lock`)

**Comment by emanuele6** [comment]
Now it should be ok to merge.
The website can still be built using the deprecated jinja2 features; and I can build `jq.1` because the lxml package is bumped to a version compatible with python 3.11.

**Comment by nicowilliams** [comment]
Thanks!

**Pull request merged**
