### PR TITLE
Makefile.am: fix lines indented with tabs instead of spaces

### PR DESCRIPTION
**Pull request by emanuele6**

### CODE REVIEW

**Review by wader — APPROVED** [review]

**Comment by nicowilliams** [comment]
Is it a problem?  I mean, I don't mind, I just never knew this to be a problem.

**Comment by emanuele6** [comment]
No, the only problem is that the text is not alligned correctly if your tab width is not 8.
Only the first line of a command for a make rule must be indented with a TAB.

**Comment by emanuele6** [comment]
Most of the other lines in the file are indented with spaces, but those were indented with tabs; probably because `vim` disables expand tabs in Makefiles and Automake files by default.

**Comment by nicowilliams** [comment]
> No, the only problem is that the text is not alligned correctly if your tab width is not 8.

I've tried doing that, but mostly I find it drives me nuts, so little sympathy here :laughing:

**Comment by emanuele6** [comment]
Yeah, I never change my tab width either. ^^

Anyway, with tab indentation those lines looked misaligned even with tab width not equal to 8 in e.g. `git diff` output where each code line is prefixed with a `+`, `-` or ` ` character:
file

---

P.S. Today, I learned that you can set the width of tabs in your terminal to have different sizes! The `tabs` command even has a `-d` option to display a ruler that shows where the tabs are located. :o
```console
$ tabs 1,20,30,35,38,50,70
$ printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' a hello HI X LOL foo bar
a                  hello     HI   X  LOL         foo                 bar
$ tabs -d 1,20,30,35,38,50,70
tabs 1,20,30,35,38,50,70
----+----1----+----2----+----3----+----4----+----5----+----6----+----7----+----8
*------------------*---------*----*--*-----------*-------------------*----------
*                  *         *    *  *           *                   *         +
```
Cool!

**Comment by wader** [comment]
@emanuele6 huh, didn't know about it either

**Comment by nicowilliams** [comment]
TIL also.  In particular I never knew about `tabs(1)`!

**Pull request merged**
