### PR TITLE
improve index, rindex and indices against string to count the index by utf8 characters

### PR DESCRIPTION
**Pull request by itchyny**
This is a fix for  #1430 and #1624 to resolve confusing byte index.

### CODE REVIEW

**Comment by nicowilliams** [comment]
@itchyny why did you close this?

**Comment by itchyny** [comment]
Because I think this will not be merged in the near future due to this comment https://github.com/stedolan/jq/issues/1624#issuecomment-498491794 (I still think it's worth changing the behavior though).

**Comment by nicowilliams** [comment]
Ah, yes, of course.  Thanks.

**Comment by emanuele6** [comment]
This is a fix for #1430.

Do we want to merge this, or close that issue?

**Comment by nicowilliams** [comment]
> This is a fix for #1430.
> 
> Do we want to merge this, or close that issue?

Great question.  String indexing is fraught; maybe we shouldn't have it at all!  But if we'll have it we should definitely have:

 - index by nth glyph
 - index by nth codepoint

and maybe:

 - index by nth byte (because it's all UTF-8, and indexing by byte in Unicode-aware apps may make sense)

That we have indexing by nth byte is essentially a design bug born of not having enough Unicode functionality.

**Comment by emanuele6** [comment]
@nicowilliams 

I think we should change the behaviour of `index` to make `.[index("a"):]` work as expected, since string slice indexing is by nth unicode codepoint, otherwise `index`/`rindex`/`indices` are pretty much useless for strings. That is also how `index` functions work in `gojq`/`fq`.

**Pull request closed without merging**
