### PR TITLE
Omit unnecessary matrix variables in the CI workflow

### PR DESCRIPTION
**Pull request by itchyny**
Ref: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

### CODE REVIEW

**Review by wader — APPROVED** [review]

**Comment by itchyny** [comment]
Ah, this change requires the branch protection rule to be changed, and existing PRs need to be rebased after merging 😢

**Comment by wader** [comment]
@itchyny not sure i followed how this was connected to branch protection rules? is it about that github actions is not smart enough to see that it won't change what jobs to run etc?

**Comment by itchyny** [comment]
@wader 
The required status checks are configured by the check names, and they are generated by the matrix variables. Now it is configured as `linux (amd64)` is required, but the status checks reported by this PR was `linux (amd64, x86_64-linux-gnu)`. Probably if the check names are generated by the include configurations if the matrix variables do not exist. We can't configure OR condition for the required status checks (if possible, it would be great), so possible solution (not to force others rebase their PRs) is to remove the requirements for while and then re-configure the check requirements.

**Comment by wader** [comment]
Aha i see, that is messy hmm, thanks for explaining

**Pull request closed without merging**
