### PR TITLE
Validate module metadata to be an object

### PR DESCRIPTION
**Pull request by itchyny**
Module metadata should be an object so we should validate module directive just as import directive.

### CODE REVIEW

**Comment by owenthereal** [comment]
LGTM

**Comment by nicowilliams** [comment]
Ah, can you rebase and re-gen the bison outputs?

**Comment by itchyny** [comment]
Do I need to use older version of Bison?

**Comment by nicowilliams** [comment]
> Do I need to use older version of Bison?

No.  Any version will do provided it works.

**Comment by itchyny** [comment]
Thank you. I rebased and confirmed `make check` passes on Ubuntu environment.

**Comment by itchyny** [comment]
Sorry, I rebased again to generate by the latest Bison (3.8.2).

**Review by wader — APPROVED** [review]

**Comment by itchyny** [comment]
Thank you.

**Pull request merged**
