### PR TITLE
feat: Add an up button in the footer of documentation pages

### PR DESCRIPTION
**Pull request by GustavoOM**

### CODE REVIEW

**Comment by emanuele6** [comment]
This adds a button at the very bottom of pages to go back up?
file

**Comment by GustavoOM** [comment]
> This adds a button at the very bottom of pages to go back up? file

Yes, that's it. Do you have any sugestions?

**Comment by wader** [comment]
How common is this on other pages? personally not sure i need it

**Comment by itchyny** [comment]
Please explain why you need this button. I think home button works well and that's enough. Having said that, current implementation lacks accessibility consideration, users can't tell its purpose on focusing into this button, and the button overwrap the menu button on mobile view.

**Comment by emanuele6** [comment]
stale

**Pull request closed without merging**
