### PR TITLE
builtin.jq: lpad, nwise

### PR DESCRIPTION
**Pull request by pkoppstein**
lpad: left pad
Retain _nwise for backward compatibility.

### CODE REVIEW

**Comment by nicowilliams** [comment]
> Retain _nwise for backward compatibility.

No need.  If it starts with an `_` then it's jq-private.

**Comment by pkoppstein** [comment]
>  If it starts with an _ then it's jq-private.

True, but so far as I know, there's hardly any cost to retaining it for now, whereas removing it for a point release would probably just be aggravating to anyone like me who has many scripts that use it.  

So my thought was: jettison it in 2.0 but in the meantime, isn't it nice to know there's some extra baggage that can be thrown overboard if that becomes necessary?

**Comment by wader** [comment]
Should we open an issue discussing possible additional convenience builtins for post 1.7? but i think we should be careful to not clutter the namespace too much. `nwise` looks like a good candidiate, i have `chunk` in fq that works similar, would gladly replace it. See https://github.com/wader/fq/blob/master/doc/usage.md#function-added-in-fq for some other additional ones i've come to use a lot.

**Comment by nicowilliams** [comment]
> Should we open an issue discussing possible additional convenience builtins for post 1.7? but i think we should be careful to not clutter the namespace too much. `nwise` looks like a good candidiate, i have `chunk` in fq that works similar, would gladly replace it. See https://github.com/wader/fq/blob/master/doc/usage.md#function-added-in-fq for some other additional ones i've come to use a lot.

Yes, I think maybe we should adopt a change freeze so we can focus on making a release.  This weekend I'll put time into re-generating the release key (or changing its name) and then making GitHub Actions workflows sign artifacts.  Why not right now?  Because I need a solid chunk of time to figure out the details.  I find working with CI/CDs to be very time consuming.  Working on features as time allows is much easier by comparison.  I think release mechanics and misc bugs (and any other bugs found by fuzzing in the next few days) should be the only things we should focus on until we get a release done.

**Comment by pkoppstein** [comment]
Since one of the "checks" was (mysteriously) unsuccessful, and since this PR is already quite old,
and since I also wanted to add a stream-oriented nwise/2, I'm closing it in favor of https://github.com/jqlang/jq/pull/2786

In this superseding PR, I've dropped both _nwise/1 and _nwise/2 (in accordance with remarks made by @nicowilliams),
but I'd be happy to add either or both of them back.

**Pull request closed without merging**
