### PR TITLE
Update git submodule commit of oniguruma from 5a24a49 to 078f95e

### LINKED ISSUE #2558: One example under Regular expressions (PCRE) doesn't work
**Describe the bug**

Under [Regular expressions (PCRE)](https://stedolan.github.io/jq/manual/v1.6/#RegularexpressionsPCRE):

>Note that certain flags may also be specified within REGEX, e.g.
> *   jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?-i)st" )'
>
>evaluates to: true, true, false, false.

However, it resulted in failure using `jq-1.6`:

```jq
$ jq -n '("test", "TEst", "teST", "TEST") | test( "(?i)te(?-i)st" )'
jq: error (at <unknown>): Regex failure: invalid group name <>
```
**Expected behavior**

The example should work.

**Environment (please complete the following information):**
 - OS and Version: [e.g. macOS, Windows, Linux (please specify distro)]
 
 ```bash
$ jq --version
jq-1.6

$ uname -a
Darwin ... 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64
```

### PR DESCRIPTION
**Pull request by hansonchar**
This change fixes https://github.com/stedolan/jq/issues/2558 by upgrading the git sub-module to include the changes of https://github.com/kkos/oniguruma/issues/282.

```bash
$ uname -a
Darwin ... 21.6.0 Darwin Kernel Version 21.6.0: Mon Dec 19 20:44:01 PST 2022; root:xnu-8020.240.18~2/RELEASE_X86_64 x86_64

$ git rev-parse HEAD
bfaa71a490a11944e76d3cf58fc0aa0870704eaa

$ git submodule update --init
$ autoreconf -fi
$ ./configure --with-oniguruma=builtin
$ make -j$(nproc)
$ make check
```

All tests passed.

### CODE REVIEW

**Comment by hansonchar** [comment]
The CI/CD failed for some seemingly unrelated reasons:
```
==> Checking msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig...
gpg: no valid OpenPGP data found.
gpg: the signature could not be verified.
Please remember that the signature file (.sig or .asc)
should be the first file given on the command line.
==> ERROR: The signature identified by msys2-keyring-r21.b39fb11-1-any.pkg.tar.xz.sig could not be verified.
Command exited with code 1
```

**Comment by wader** [comment]
Yeap has been broken for a while :( thanks for PR! and looking at the oniguruma release notes i have a feeling this fixes a bunch of other bugs and security issues.

**Comment by owenthereal** [comment]
@hansonchar Would you mind rebasing this PR on the latest master? It now has a passing CI so we could verify whether this PR would break anything.

**Comment by owenthereal** [comment]
@hansonchar We fixed some GH Actions permissions that prevented the CI from starting (see below). Would you mind running a `git commit --amend` and then force push to trigger the CI again? Sorry about the inconvenience, and I really wish there was another way we could trigger it from our side without you doing it.

Screenshot 2023-06-01 at 1 45 29 PM

**Review by itchyny — APPROVED** [review]

**Comment by owenthereal** [comment]
LGTM

**Pull request merged**
